#!/usr/bin/env bash
# Regenerate every page that quotes something a bot collects, and push it as its own commit.
#
#   bash .github/scripts/regenerate-derived.sh "Snapshot 2026-09-22"   # CI: commit + push
#   bash .github/scripts/regenerate-derived.sh regenerate               # local: files only
#
# WHY THIS EXISTS. On 2026-09-21 each scheduled bot left master red, differently:
# snapshot.yml moved the archive's day count, which docs/SCORECARD.md quotes, and
# regenerated nothing (503b7a6); production.yml moved the live unknown rate and regenerated
# three of the four pages that quote it (c66c6be) -- a hand-typed list, one generator short.
# Two bots, two lists, both incomplete. This is the one list, and
# tests/test_bot_commits_stay_green.py derives from the generators' own sources what it
# must contain, so the next generator that reads bot data is required here automatically.
#
# WHY A SEPARATE COMMIT, PUSHED LAST. The data commit is irreplaceable and the snapshot
# bot's rebase is only safe because it appends to files no human edits. The pages below
# ARE regenerated by humans, so a commit carrying both could conflict and take a pass of
# rows down with it. Callers push their data first; only then does this run.
#
# WHY RESET RATHER THAN REBASE. These pages are a pure function of the tree they are
# generated from. When a push is rejected, the right commit is not ours replayed onto the
# new base -- it is the pages regenerated FROM the new base. So each attempt throws its
# commit away, takes origin's head, and regenerates. It refuses to start if the runner
# holds a commit that never reached origin: that could only be data whose push failed, and
# a reset would destroy the only copy.
set -uo pipefail

mode="${1:-}"
ref="${GITHUB_REF_NAME:-master}"

regenerate() {
  # A fixed point, at most three passes: publish_numbers reads the maturity total out of
  # docs/SCORECARD.md, which scorecard.py rewrites, so one pass in either order can leave
  # the other a step behind.
  local pass before after
  for pass in 1 2 3; do
    before=$(git diff --binary | md5sum)
    python bench/scorecard.py --write >/dev/null || { echo "::error::scorecard.py failed"; return 1; }
    python bench/publish_numbers.py --write >/dev/null || { echo "::error::publish_numbers.py failed"; return 1; }
    python tools/owner.py --write >/dev/null || { echo "::error::owner.py failed"; return 1; }
    python tools/rounds.py --write >/dev/null || { echo "::error::rounds.py failed"; return 1; }
    after=$(git diff --binary | md5sum)
    if [ "$before" = "$after" ]; then
      return 0
    fi
  done
  echo "::warning::the derived pages were still changing after three passes"
  return 0
}

if [ "$mode" = "regenerate" ]; then
  regenerate
  exit $?
fi
if [ -z "$mode" ]; then
  echo "usage: regenerate-derived.sh '<commit subject prefix>' | regenerate" >&2
  exit 2
fi

git config user.name "vetagent-derived[bot]"
git config user.email "noreply@vetagent.dev"

if ! git fetch --quiet origin "$ref"; then
  echo "::error::could not fetch origin/${ref}; the data is pushed, the derived pages are not"
  exit 1
fi
unpushed=$(git rev-list --count "origin/${ref}..HEAD")
if [ "$unpushed" != "0" ]; then
  echo "::warning::${unpushed} local commit(s) never reached origin -- not regenerating over them"
  exit 0
fi

for attempt in 1 2 3 4 5; do
  git reset --quiet --hard "origin/${ref}"
  if ! regenerate; then
    echo "::error::the data is pushed; the derived pages could not be regenerated"
    exit 1
  fi
  if [ -n "$(git diff --name-only -- src/)" ]; then
    # A bot push touching src/ would deploy. Nothing a bot collects feeds a figure there,
    # so this means a generator has changed shape, and a human should look.
    echo "::error::regeneration changed src/, which a bot must never push:"
    git diff --stat -- src/
    exit 1
  fi
  if git diff --quiet; then
    echo "the derived pages are already current"
    exit 0
  fi
  git add -u -- . ':!src'
  git commit --quiet -m "${mode} (derived pages): regenerate what this run moved"
  if git push --quiet origin "HEAD:${ref}"; then
    echo "pushed on attempt ${attempt}"
    exit 0
  fi
  echo "::notice::push rejected (attempt ${attempt}); regenerating on the new base"
  sleep $(( attempt * 10 ))
  git fetch --quiet origin "$ref" || true
done

echo "::error::could not push the derived pages after 5 attempts; the data is already pushed"
exit 1
