"""og_image.py -- generate the 1200x630 share card served at /og.png.

Usage:
    python tools/og_image.py            # writes src/og_image.py (base64 PNG) and a preview PNG

Why generated, and why no numbers on it
---------------------------------------
Links to vetagent.dev were shared with no preview image at all (no og:image, no
twitter:card; GEO baseline 2026-09-15). The card carries identity only -- no accuracy figure --
because a number baked into a PNG is the one kind of published number the number guard cannot
read, and every figure this project publishes has to be checkable.

Fonts: Segoe UI and Consolas, read from C:/Windows/Fonts on the machine that generates the card.
The Worker never renders it; it serves the committed bytes. Regenerate after changing the text.
"""

import base64
import io
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT_MODULE = os.path.join(ROOT, "src", "og_image.py")
FONTS = "C:/Windows/Fonts"

W, H = 1200, 630
BG, PANEL, LINE = (11, 17, 16), (17, 25, 23), (30, 43, 41)
TXT, DIM, ACCENT = (221, 231, 228), (138, 160, 156), (63, 191, 170)
OK, WARN, CRIT = (79, 177, 131), (210, 160, 63), (224, 115, 106)


def font(name, size):
    return ImageFont.truetype(os.path.join(FONTS, name), size)


def render():
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, W, 8], fill=ACCENT)
    d.text((80, 92), "VetAgent", font=font("segoeuib.ttf", 96), fill=TXT)
    d.text((84, 222), "Pre-trade token risk check for AI agents", font=font("segoeui.ttf", 46),
           fill=TXT)
    d.text((84, 290), "Honeypot simulation · taxes · liquidity depth · impersonation",
           font=font("segoeui.ttf", 30), fill=DIM)

    # The four verdicts, as an agent reads them.
    x = 84
    for label, colour in (("low", OK), ("medium", WARN), ("high", CRIT), ("unknown", DIM)):
        f = font("consolab.ttf", 30)
        w = d.textlength(label, font=f)
        d.rounded_rectangle([x, 372, x + w + 36, 422], radius=10, outline=colour, width=3)
        d.text((x + 18, 377), label, font=f, fill=colour)
        x += w + 60

    d.rectangle([80, 470, W - 80, 472], fill=LINE)
    d.text((84, 500), "MCP  https://vetagent.dev/mcp", font=font("consola.ttf", 32), fill=ACCENT)
    d.text((84, 548), "Free · no key · published, reproducible error rate",
           font=font("segoeui.ttf", 28), fill=DIM)
    return img


def main():
    img = render()
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    data = buf.getvalue()
    b64 = base64.b64encode(data).decode("ascii")
    lines = [b64[i:i + 96] for i in range(0, len(b64), 96)]
    with open(OUT_MODULE, "w", encoding="utf-8", newline="\n") as f:
        f.write('"""The /og.png share card. Generated by tools/og_image.py -- do not edit."""\n\n')
        f.write("import base64\n\n")
        f.write("PNG = base64.b64decode(\n")
        for line in lines:
            f.write('    "%s"\n' % line)
        f.write(")\n")
    preview = os.path.join(ROOT, "assets", "og-preview.png")
    os.makedirs(os.path.dirname(preview), exist_ok=True)
    with open(preview, "wb") as f:
        f.write(data)
    print("wrote %s (%d bytes PNG) and %s" % (OUT_MODULE, len(data), preview))


if __name__ == "__main__":
    main()
